# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "playground-portal-helpers"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lashd"]
  s.date = "2013-03-23"
  s.description = "helpers"
  s.email = "leon_a_d@yahoo.com"
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "VERSION",
    "helpers.iml",
    "lib/playground/portal/helpers/http_operations.rb",
    "lib/playground/portal/helpers/memcache_operations.rb",
    "playground-portal-helpers.gemspec",
    "rakefile"
  ]
  s.homepage = "https://github.com/lashd/playground.git"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "helpers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

